#!/usr/bin/env python3
"""
generate_readme.py

Scans all .java files in the repository, figures out which DSA topic
each one belongs to, and regenerates README.md with a topic-organized
table of problems.

Topic detection priority:
  1. A "// Topic: <name>" comment at the top of the file (most accurate)
  2. Keyword matching against the filename (fallback for older files)
  3. "Uncategorized" if nothing matches
"""

import os
import re
import glob

REPO_ROOT = "."  # run from repo root
OUTPUT_FILE = "README.md"

# Order matters: more specific keywords should come before general ones.
# Each tuple is (Topic Name, [keywords to match in filename, lowercase])
TOPIC_KEYWORDS = [
    ("Binary Search", ["binarysearch", "lowerbound", "upperbound", "searchinsert",
                        "searchmatrix", "findkrotation", "checkifarrayissorted",
                        "findminimuminrotated", "searchinrotated"]),
    ("Matrix", ["matrix", "diagonalsum", "spiral", "rotateimage", "setmatrixzero"]),
    ("Sorting", ["mergesort", "quicksort", "heapsort", "countinversions", "reversepairs"]),
    ("Two Pointers / Hashing", ["3sum", "4sum", "twosum"]),
    ("Math", ["gcd", "happynumber", "palindromenumber", "powerof", "pascaltriangle",
              "angle", "maximumachievable"]),
    ("Strings", ["reversestring", "string"]),
    ("Arrays", ["majorityelement", "maximumproduct", "mergeinterval", "mergesortedarray",
                "nextpermutation", "rearrangearray", "removeduplicates", "removeelement",
                "rotatearray", "longestconsecutive"]),
]


def detect_topic_from_comment(file_content):
    """Look for a '// Topic: <name>' comment in the first few lines."""
    for line in file_content.splitlines()[:5]:
        match = re.match(r"\s*//\s*Topic:\s*(.+)", line, re.IGNORECASE)
        if match:
            return match.group(1).strip()
    return None


def detect_topic_from_filename(filename):
    """Fallback: guess the topic using keyword matching on the filename."""
    lower_name = filename.lower()
    for topic, keywords in TOPIC_KEYWORDS:
        for kw in keywords:
            if kw in lower_name:
                return topic
    return "Uncategorized"


def detect_problem_name_from_comment(file_content):
    """Look for a '// Problem: <name>' comment in the first few lines."""
    for line in file_content.splitlines()[:5]:
        match = re.match(r"\s*//\s*Problem:\s*(.+)", line, re.IGNORECASE)
        if match:
            return match.group(1).strip()
    return None


def filename_to_problem_name(filename):
    """Convert a filename like 'FindMinimumInRotatedSortedArrayJava.java'
    into a readable problem name: 'Find Minimum In Rotated Sorted Array'.
    Handles acronyms like 'GCD' correctly (won't split into 'G C D')."""
    base = filename.replace(".java", "")
    base = re.sub(r"Java$", "", base)  # strip trailing "Java" suffix
    # Insert a space between a lowercase/digit and a following uppercase letter,
    # and between an acronym (multiple caps) and the next Capitalized word.
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", base)
    spaced = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", spaced)
    return spaced.strip()


def scan_java_files():
    """Scan all .java files and group them by topic."""
    topics = {}
    java_files = sorted(glob.glob(os.path.join(REPO_ROOT, "*.java")))

    for filepath in java_files:
        filename = os.path.basename(filepath)
        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()

        topic = detect_topic_from_comment(content) or detect_topic_from_filename(filename)
        problem_name = detect_problem_name_from_comment(content) or filename_to_problem_name(filename)

        topics.setdefault(topic, []).append((problem_name, filename))

    return topics


def build_readme(topics):
    """Build the README.md content from the topic -> [(problem, file)] mapping."""
    total_count = sum(len(v) for v in topics.values())

    lines = []
    lines.append("# DSA Practice\n")
    lines.append("A collection of Data Structures & Algorithms problems solved in **Java**, "
                  "primarily from LeetCode — covering arrays, binary search, sorting, matrices, and more.\n")
    lines.append("![Java](https://img.shields.io/badge/Java-ED8B00?style=for-the-badge&logo=openjdk&logoColor=white)")
    lines.append("![DSA](https://img.shields.io/badge/DSA-Practice-blue?style=for-the-badge)\n")
    lines.append("---\n")
    lines.append("## 📊 Progress\n")
    lines.append(f"**{total_count} problems solved**, organized by topic below.\n")
    lines.append("> This README is auto-generated by `generate_readme.py` — do not edit it directly.\n")
    lines.append("---\n")
    lines.append("## 📂 Problems by Topic\n")

    # Sort topics for consistent ordering, "Uncategorized" always last
    sorted_topics = sorted(topics.keys(), key=lambda t: (t == "Uncategorized", t))

    for topic in sorted_topics:
        problems = sorted(topics[topic], key=lambda p: p[0])
        lines.append(f"### {topic}")
        lines.append("| Problem | File |")
        lines.append("|---|---|")
        for problem_name, filename in problems:
            lines.append(f"| {problem_name} | `{filename}` |")
        lines.append("")

    lines.append("---\n")
    lines.append("## 🛠️ Tech Stack\n")
    lines.append("- **Language:** Java")
    lines.append("- **Source:** LeetCode\n")
    lines.append("---\n")
    lines.append("## 👤 Author\n")
    lines.append("**Ashish Tiwari**")
    lines.append("[GitHub](https://github.com/mt320236) · "
                  "[LinkedIn](https://linkedin.com/in/ashish-tiwari-49056238b) · "
                  "[LeetCode](https://leetcode.com/at320236)")

    return "\n".join(lines)


def main():
    topics = scan_java_files()
    readme_content = build_readme(topics)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(readme_content)

    total = sum(len(v) for v in topics.values())
    print(f"✅ README.md generated with {total} problems across {len(topics)} topics.")


if __name__ == "__main__":
    main()
